name: file changes

on: 
  push:
    branches:
    - develop

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
          fileOutput: ' '
      - name: test
        run: |
          ls -l $HOME
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
