name: file changes

on: 
  push:
    branches:
    - develop

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
          java-package: jre
      - run: keytool --help
        
